name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # ✅ CORRIGIDO

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
